//
//  CardPresenter.swift
//  StockMonitoring
//
//  Created by Александр on 18.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardPresentationLogic
{
  func Stock(response: Card.GetStock .Response)
}

class CardPresenter: CardPresentationLogic
{
  weak var viewController: CardDisplayLogic?
  
  // MARK: Display stock
    
  func Stock(response: Card.GetStock.Response)
  {
    let stock = response.stock
    if stock.price != nil,
       stock.change != nil,
       stock.changePercent != nil,
       stock.nameCompany != nil {
      
      let title = getAttributedString(string: String(stock.ticker), font: UIFont(name: "Montserrat-Bold", size: 18)!)
      let shortName = getAttributedString(string: String(stock.nameCompany!), font: UIFont(name: "Montserrat-Bold", size: 12)!)
      title.append(NSAttributedString(string: "\n"))
      title.append(shortName)
      let regularMarketPrice = Double(round(100*stock.price!)/100)
      let regularMarketChange = Double(round(100*stock.change!)/100)
      let regularMarketChangePercent = Double(round(100*stock.changePercent!)/100)
      
      let displayedStock = Card.GetStock.ViewModel.DisplayedStock(title: title, regularMarketPrice: regularMarketPrice, regularMarketChange: regularMarketChange, regularMarketChangePercent: regularMarketChangePercent, isFavourite: stock.isFavourite)
      let viewModel = Card.GetStock.ViewModel(displayedStock: displayedStock)
      viewController?.displayStock(viewModel: viewModel)
    }

  }
    
    func getAttributedString(string: String, font: UIFont) -> NSMutableAttributedString {
        let paramString = [NSAttributedString.Key.font : font]
        return NSMutableAttributedString(string: string, attributes: paramString as [NSAttributedString.Key : Any])
    }
}
