//
//  CardModels.swift
//  StockMonitoring
//
//  Created by Александр on 18.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Card
{
  // MARK: Use cases
  
  enum GetStock
  {
    struct Request
    {
    }
    struct Response
    {
        var stock: Stock
    }
    struct ViewModel
    {
      struct DisplayedStock
      {
        let title: NSMutableAttributedString?
        let regularMarketPrice: Double?
        let regularMarketChange: Double?
        let regularMarketChangePercent: Double?
        let isFavourite: Bool
      }
      var displayedStock: DisplayedStock
    }
  }
    
        struct StockFormFields
        {
            var changePercent: Double
            var isFavourite: Bool
            var nameCompany: String?
            var price: Double
            var ticker: String?
            var change: Double
        }
    
    enum FetchStocks
    {
      struct Request
      {
      }
      struct Response
      {
        var stocks: [Stock]
      }
      struct ViewModel
      {
      }
    }

    
    enum StockIsFavouriteChange
    {
      struct Request
      {
      }
      struct Response
      {
        var stock: Stock
      }
      struct ViewModel
      {
      }
    }
}

