//
//  StockPresenter.swift
//  StockMonitoring
//
//  Created by Александр on 30.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StockPresentationLogic
{
    func presentData(response: StockModel.Model.Response.ResponseType)
}

class StockPresenter: StockPresentationLogic
{
  weak var viewController: StockDisplayLogic?
  
  // MARK: Do something
  
    func presentData(response: StockModel.Model.Response.ResponseType)
  {
        switch response {
        
        case .presentStocks(stocksResponse: let stocks):
            let cells = stocks.map { (stock) in
                cellViewModel(from: stock)
            }
            let stockViewModel = StockViewModel.init(cells: cells)
            viewController?.displayData(viewModel: StockModel.Model.ViewModel.ViewModelData.displayStock(stockViewModel: stockViewModel) )
            
        case  .hideActivityIndicator:
            viewController?.displayData(viewModel: StockModel.Model.ViewModel.ViewModelData.hideActivityIndicator )
        }
        
        
  }
    
        private func cellViewModel(from stock: Stock) -> StockViewModel.Cell {
        return StockViewModel.Cell.init(ticker: stock.ticker,
                                        name: stock.nameCompany,
                                        price: stock.price,
                                        change: stock.change,
                                        changePercent: stock.changePercent,
                                        isFavorite: stock.isFavourite)
    }
}
