//
//  StockModels.swift
//  StockMonitoring
//
//  Created by Александр on 30.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StockModel
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType {
            case getStocks(requestNeedsCancel: Bool)
            case getFavouriteStocks
            case getSearch(request: String)
        }
    }
    struct Response
    {
        enum ResponseType {
            case presentStocks(stocksResponse: [Stock])
            case hideActivityIndicator

        }
    }
    struct ViewModel
    {
        enum ViewModelData {
            case displayStock(stockViewModel: StockViewModel)
            case hideActivityIndicator
        }
    }
  }
}

struct StockViewModel {
    struct Cell: StockCellViewModel {
        var ticker: String?
        var name: String?
        var price: Double?
        var change: Double?
        var changePercent: Double?
        var isFavorite: Bool?
    }
    
    let cells: [Cell]
}
