//
//  StockModels.swift
//  StockMonitoring
//
//  Created by Александр on 30.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Stock
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType {
            case getStocks
        }
    }
    struct Response
    {
        enum ResponseType {
            case presentStocks(stocksResponse: [MostWatchedTickers])
        }
    }
    struct ViewModel
    {
        enum ViewModelData {
            case displayStock(stockViewModel: StockViewModel)
        }
    }
  }
}

struct StockViewModel {
    struct Cell: StockCellViewModel {
        var ticker: String
        
        var name: String?
        
        var price: String?
        
        var change: String?
        
        var changePercent: String?
        
        var favorite: Bool
        
        
    }
    
    let cells: [Cell]
}
